### ISSUE TITLE
table cache does not exists

### ISSUE THREAD

**Issue by jsmith432** [alexjustesen/speedtest-tracker#1096]
Brand new installation, tried with postgresql and mariadb, both complained about cache not existing: 

stdout
02/03/2024
12:33:19 PM
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'speedtest_tracke  
stdout
02/03/2024
12:33:19 PM
  r.cache' doesn't exist (Connection: mysql, SQL: delete from `cache`)

**Comment by AlbertCaro** [comment]
I encountered the same issue, but I hadn't configured the container to use MySQL; I was using PostgreSQL instead.:

`In Connection.php line 829:

  SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: delete f
  rom `cache`)


In Connector.php line 65:

  SQLSTATE[HY000] [2002] Connection refused`

It happens after v0.16.6 comes out, I used the "latest" tag in my Docker Compose file. I resolved the issue by reverting back to v0.16.5.

This gives a strong indication that the bug was likely introduced in version v0.16.6.

**Comment by nicandris** [comment]
looks like there is a new release out disabling clearing cache on boot so this should be fixed. 
I actually spent quite some time on the same issue yesterday, tried maria/sql/postgress and it was the same error. If it still doesn't work with the new release, you can boot by setting the cache_driver var to "file", boot, and then change it to "database"

**Comment by Suyknow** [comment]
add the Env CACHE_DRIVER=file
it's ok for me.

**Comment by alexjustesen** [comment]
If you're getting a message that you're missing the cache table, upgrade to `v0.14.6`. After that you should set `CACHE_DRIVER=database` and restart the container.

If you still get the error run `php artisan db:show` in the container's terminal to verify the existence of the cache tables (hint there will be two `cache` and `cache_locks`).

**Comment by AlbertCaro** [comment]
> If you're getting a message that you're missing the cache table, upgrade to `v0.14.6`. After that you should set `CACHE_DRIVER=database` and restart the container.
> 
> If you still get the error run `php artisan db:show` in the container's terminal to verify the existence of the cache tables (hint there will be two `cache` and `cache_locks`).

It works, thank you so much 😄

**Comment by wdog** [comment]
I just fixed changing the migration order. I put "cache" table creation as first, just renaming `2013_01_05_205157_create_cache_table`
