### ISSUE TITLE
Email failing with STARTTLS error, even though encryption is set to 'null'

### ISSUE THREAD

**Issue by adhawkins** [alexjustesen/speedtest-tracker#1118]
When I configure SMTP delivery, it's trying to make a TLS connection, which my local mail server isn't configured for.

This is the .env file in the config directory:

```
MAIL_MAILER=smtp
MAIL_HOST=localmail.gently.org.uk
MAIL_PORT=25
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="speedtest@gently.org.uk"
MAIL_FROM_NAME="Speedtest Tracker"
```

This is the error I get when 'test' sending an email:

```
speedtest  | [2024-02-09 17:21:54] production.ERROR: Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
speedtest  | error:0A000086:SSL routines::certificate verify failed {"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 0): Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
speedtest  | error:0A000086:SSL routines::certificate verify failed at /app/www/vendor/symfony/mailer/Transport/Smtp/Stream/SocketStream.php:171)
```

As I have `MAIL_ENCRYPTION` set to `null`, I wouldn't expect it to attempt TLS negotiation.

**Comment by alexjustesen** [comment]
Are you sure the ports are correct? Most SMTP services require SSL or TLS

**Comment by adhawkins** [comment]
Absolutely. This is an SMTP server accessible solely from my local network for delivering internal email. There is no encryption configured whatsoever, just plain SMTP on port 25.

**Comment by alexjustesen** [comment]
Try setting `MAIL_ENCRYPTION=false`, seems Symphony will take `null` and default it to `tls`.

Source: https://github.com/laravel/framework/issues/44953

**Comment by kuya1284** [comment]
I came here to report a similar, possibly the same issue as what's described. I tried @alexjustesen suggestion of using `false` instead of `null`, which did not seem to make a difference. I also discovered a difference in behavior when using an **IP Address** versus an **FQDN**. When specifying `MAIL_HOST` using an **IP address**, the mail attempt fails. When I set `MAIL_HOST` using a **FQDN** instead, emails get sent via my Postfix server without issues.

Here's what I see in my Postfix server logs (real hostname and IP redacted):

```
> connect from <SOURCE HOSTNAME>[<SOURCE IP>] 
> Anonymous TLS connection established from <SOURCE HOSTNAME>[<SOURCE IP>]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature ECDSA (P-384) server-digest SHA384
> OTP unavailable because can't read/write key database /etc/opiekeys: Permission denied
> lost connection after STARTTLS from <SOURCE HOSTNAME>[<SOURCE IP>]
> disconnect from <SOURCE HOSTNAME>[<SOURCE IP>] ehlo=1 starttls=1 commands=2
```

I also noticed that when using the IP address, **three attempts** get made. The source IP of the first attempt is the Docker container's IP, then the other two are from the host's IP. When using the Postfix FQDN instead, only **one attempt** gets made, and again, that works without issues.

**Comment by kuya1284** [comment]
The issue described in my previous comment persisted when I upgraded to `v0.15.3`.

**Comment by alexjustesen** [comment]
Can you try passing the environment variable `MAIL_VERIFY_SSL=false` into your container? You can still set `MAIL_ENCRYPTION=false`.

**Comment by kuya1284** [comment]
@alexjustesen that worked! I tested with both `MAIL_ENCRYPTION=null` and `MAIL_ENCRYPTION=false`, and was able to receive my test emails using an IP Address. It looks like `MAIL_VERIFY_SSL=false` was the critical missing piece to the puzzle. Thank you!

**Comment by adhawkins** [comment]
I've just nuked my config, and started again with the settings specified as environment variables in the docker-compose.yaml file. All seems to be working correctly now.
