### ISSUE TITLE
Results are displayed in Gbps

### ISSUE THREAD

**Issue by dtech77pl** [alexjustesen/speedtest-tracker#1211]
Results are displayed in Gbps
Can this be rolled back to Mbps? 
![Gbps](https://github.com/alexjustesen/speedtest-tracker/assets/122393484/c5e0c196-fae2-4c1c-af29-20cb89ff584d)

**Comment by alexjustesen** [comment]
Check out https://github.com/alexjustesen/speedtest-tracker/issues/1186#issuecomment-1954562242 as this is intentional.

**Comment by dtech77pl** [comment]
I have the latest version 0.16.6 and still this display issue exist.

**Comment by alexjustesen** [comment]
It's not an issue, it's rounding to the next order of magnitude on purpose. 

940 Mbps === 0.94 Gbps.

**Comment by OddSquirrel** [comment]
Mind you, this is your project, and you can run it exactly the way you want, but I would make a bet that an overwhelming majority would expect Mbps instead of Gbps. Simply because the world is used to it, so you aren't likely to hear the end of it anytime soon.

Granted, it might make sense if it at least had to cross the threshold to a full Gb in order to provoke a change of magnitude, but that 0.xx sure looks a bit odd. More especially so, since both values (up and down) now typically have different orders of magnitude.

Maybe a preferred setting would help? I wish I could contribute to it, but, unfortunately, I'm as thick as two short planks when it comes to this stuff. 😩

**Comment by alexjustesen** [comment]
I think with gigabit service becoming more pervasive (I have 1, 2 and 5 gbps options) this gives us some future proofing. I am going to change when it rounds to the next order of magnitude though to `> 0.99` from `> 0.9` so `940 Mbps` will be shown instead of `0.94 Gbps`.

**Comment by OddSquirrel** [comment]
Awesome, I think that's a great compromise. Thanks much! 😊
