### ISSUE TITLE
Multiple runs (warm up run)

### ISSUE THREAD

**Issue by pkirsche** [alexjustesen/speedtest-tracker#1354]
**Is your feature request related to a problem? Please describe.**
Everytime I run a manual speed test, I get around 10% better results than the periodic automatic runs. I'm using always the same server and observed this behaviour also when running the manual test only a few minutes before and after the scheduled test.

**Describe the solution you'd like**
Maybe we can have an option for multiple speedtest runs? Let's say on every scheduled run, there is not just this single test but another test where the second one then is used for logging and saving.
I would call it an additional "warm up" run :)

**Comment by c11umw** [comment]
It could possibly also relate to bufferbloat where the device calling the SpeedTest isn't being given the network priority to perform the test in full due to other network traffic already queued up or happening at that the time.

You can test it here: https://www.waveform.com/tools/bufferbloat

In theory it should be fixable with QOS enabled on your router (aka "Smart Queues" on Unifi routers)

**Comment by alexjustesen** [comment]
#1444 coming in the next version might help this.

**Comment by alexjustesen** [comment]
@pkirsche `v0.20.x` series includes pinging an IP address or domain prior to running a test, has this helped with "warming" a connection?

**Comment by pkirsche** [comment]
> @pkirsche `v0.20.x` series includes pinging an IP address or domain prior to running a test, has this helped with "warming" a connection?

Looks very good now. 👍 Moving to another time schedule already made the results more constant the last weeks, but with the new release, I added a domain to test and the results are absolutly stable and at the limit of the connection now. Very impressive, it seems it needs some traffic before the messure itself to "wake" my connection up.

Thanks!
