### ISSUE TITLE
Speedtest Tracker uses 2.4TB of data PER WEEK

### ISSUE THREAD

**Issue by primetime-sudo** [alexjustesen/speedtest-tracker#1404]
**Describe the bug**
Speedtest-tracker is using an absurd amount of data. I was using the henrywhitaker3 version for a year and never saw any data spikes. 

**To Reproduce**
Let it run hourly tests

**Expected behavior**
Data usage should be a normal amount, similar to henrywhitaker3 version. 

**Environment (please complete the following information):**
Docker on Ubuntu host machine

**Screenshots**

**Logs**
If applicable, check the logs for any error that might of occurred.

**Additional context**
I got an alert from my router software that I've been using 2.4 TB of data per week, and it started the moment I set up Speedtest-tracker 1 month ago. So I'm using 10TB of data just for Speedtest tracker alone. 

I would anticipate there to be a bit of data used for an hourly polling. I have it set to use the Portland Oregon datacenter, on a cron schedule of 0 * * * *

**Comment by svenvg93** [comment]
Speedtest CLI doesnt uses that much data. 
Looking at mine as a example, even if i run it every hour it will nowhere come close to the amout you are seeing. 

138GB download and 77GB upload per week 
   
```
Speedtest by Ookla
      Server: Odido - Amsterdam (id: 52365)
         ISP: Odido Netherlands
Idle Latency:     5.20 ms   (jitter: 0.19ms, low: 5.00ms, high: 5.56ms)
    Download:   934.41 Mbps (data used: 827.1 MB)
                 12.44 ms   (jitter: 4.03ms, low: 5.56ms, high: 233.88ms)
      Upload:   930.79 Mbps (data used: 454.9 MB)
                  6.17 ms   (jitter: 0.40ms, low: 4.90ms, high: 7.10ms)
 Packet Loss:     0.0%
```

Can you check how much data the container used by going into the container 

`docker exec -it <containername> sh`

Run uptime and ifconfig. Eth0 should show how much data it used since the container is running.
Also if you go to the results table does it show the resutls every hour, just to make sure that the cron is not running more then you set ;)

**Comment by alexjustesen** [comment]
As @svenvg93 pointed out Ookla's CLI uses about 1.2GB of data per run so you'll need to manage your usage. Henry's and mine both use the same CLI unless they've made updates.
