### ISSUE TITLE
Configure admin email/password through environment variables?

### ISSUE THREAD

**Issue by zodac** [alexjustesen/speedtest-tracker#1597]
**Is your feature request related to a problem? Please describe.**
Currently on initial startup, you need to log in with the default admin email/password, then update values.

**Describe the solution you'd like**
Configure the admin email/password/username through environment variables, so there is no need to use the UI.

**Comment by twinpixxx** [comment]
Ok, I may take this one. But what's the best way to do this? 
Currently admin user is configured through the migration (one of the first tho). I see two ways: 

1. Change current initial migration to retrieve env variables if they present. 
2. Add another one that will change existing. 

Both are not ideal, but have their own pros and cons. 

Offtop:
Also I would like to have a feature to login using username(+email)/pass rather then just email/pass, because it's kinda annoying to use email each time.


What do you think? 
CC @alexjustesen @zodac

**Comment by alexjustesen** [comment]
> 1. Change current initial migration to retrieve env variables if they present.

I would say this would be the easiest way to implement this, but at the same time I don't understand why you can't login and just change your password and email afterwards. 🤷‍♂️

> Offtop: Also I would like to have a feature to login using username(+email)/pass rather then just email/pass, because it's kinda annoying to use email each time.

I would say this is off the table, if we did username and/or email it would fundamentally change the auth process and introduce complexities.

**Comment by alexjustesen** [comment]
That all being said, I'd be happy to merge a PR if you want to add the config to the initial user migration. This way new installs can benefit from the process.
