### ISSUE TITLE
Exclude Servers

### ISSUE THREAD

**Issue by obroomhall** [alexjustesen/speedtest-tracker#161]
**Is your feature request related to a problem? Please describe.**
There is a server close to me which always gives significantly slow speed results.

**Describe the solution you'd like**
I would like to exclude the server when running a speed test. Ookla have an exclude flag for this feature:
`  --exclude EXCLUDE     Exclude a server from selection. Can be supplied multiple times`

**Additional context**
Image that shows `47230 (Vorboss Limited)` giving lower speeds than other servers. Current workaround is just to include a server that I know gives more accurate results.
![image](https://user-images.githubusercontent.com/4409652/202921088-00a3480f-9ff5-4ba6-9455-4013f11faed1.png)

**Comment by alexdelprete** [comment]
I would suggest you do the exact opposite: instead of using auto selection by speedtest with exclusions, it's much more efficient for a speedtest tracker to be able to configure a good reliable server in the options, and this is already supported.

Server selection is critical if you want reliable results, I spent quite some time selecting the best server for my area.

**Comment by obroomhall** [comment]
Closed since inclusion list is good enough for what I need

**Comment by spcqike** [comment]
@alexdelprete to add one thing: this is a request that I opened in the original speed tracker, too 

I would like to exclude bad servers only. Simple because I think that if everyone uses just the three best servers at the moment, these three servers will get overloaded and start to give low values. So in some month one starts over and searches good quality servers. 

It would be easier to just Use all servers and ignore slow ones. 

(Starting the jobs at 00:58 instead 01:00 also helps to get better results, as most cronjobs run at the full hour, but still, the workload for a server will get higher after a while. 

While I write this: maybe it’s an option to have some random delay for a task. So that the workload on the servers gets distributed over some minutes.)

**Comment by alexdelprete** [comment]
> Simple because I think that if everyone uses just the three best servers at the moment, these three servers will get overloaded and start to give low values. So in some month one starts over and searches good quality servers.

that's not been my experience using speedtest servers: I found out that the best ones are always reliable and predictable at any time of the day, even though they are very popular and used by a lot of people (I use a Vodafone server in Milan that is widely used because of its reliabaility) and it's also pretty far from my physical location, despite that I have the best latency results.

The only thing I asked the dev is to implement a list of servers, for redundancy. I think it's the best approach, at least for my experience.

Regarding the scheduling, I start my tests at minute 27, just because I know everybody uses round times (:00 or :30). The idea of a random "salt" for the start of the task is interesting, I like it.

**Comment by obroomhall** [comment]
Tried the speed test with the problematic server on Ookla's web interface, and had no issues getting full speed results.

I considered that this might be a docker networking issue even though other servers gave full speed results with docker networking, so I tried to run a speedtest against the id given in `speedtest-tracker` and was met with:

```
$ speedtest --secure --server 47230
Retrieving speedtest.net configuration...
Testing from Virgin Media (86.16.135.82)...
Retrieving speedtest.net server list...
ERROR: No matched servers: 47230
```

You can see that I used the same id as in the screenshot in the original post for this issue.

**Comment by alexdelprete** [comment]
Working here:

```
 speedtest -s 47230

   Speedtest by Ookla

      Server: Vorboss Limited - London (id: 47230)
         ISP: Tecno General S.r.l
Idle Latency:    29.67 ms   (jitter: 1.56ms, low: 27.98ms, high: 34.04ms)
    Download:    50.24 Mbps (data used: 60.9 MB)
                 28.07 ms   (jitter: 3.34ms, low: 27.53ms, high: 291.46ms)
      Upload:     2.06 Mbps (data used: 3.4 MB)
                 28.09 ms   (jitter: 0.48ms, low: 27.67ms, high: 35.88ms)
 Packet Loss: Not available.
  Result URL: https://www.speedtest.net/result/c/06c955da-acd0-4349-85d7-18a1301d2438
```

What version of speedtest-cli are you using? Here's mine:

```
❯ speedtest --help
Speedtest by Ookla is the official command line client for testing the speed and performance of your internet connection.

Version: speedtest 1.2.0.84

Usage: speedtest [<options>]
  -h, --help                        Print usage information
  -V, --version                     Print version number
  -L, --servers                     List nearest servers
  -s, --server-id=#                 Specify a server from the server list using its id
  -I, --interface=ARG               Attempt to bind to the specified interface when connecting to servers
  -i, --ip=ARG                      Attempt to bind to the specified IP address when connecting to servers
  -o, --host=ARG                    Specify a server, from the server list, using its host's fully qualified domain name
  -p, --progress=yes|no             Enable or disable progress bar (Note: only available for 'human-readable'
                                    or 'json' and defaults to yes when interactive)
  -P, --precision=#                 Number of decimals to use (0-8, default=2)
  -f, --format=ARG                  Output format (see below for valid formats)
      --progress-update-interval=#  Progress update interval (100-1000 milliseconds)
  -u, --unit[=ARG]                  Output unit for displaying speeds (Note: this is only applicable
                                    for ‘human-readable’ output format and the default unit is Mbps)
  -a                                Shortcut for [-u auto-decimal-bits]
  -A                                Shortcut for [-u auto-decimal-bytes]
  -b                                Shortcut for [-u auto-binary-bits]
  -B                                Shortcut for [-u auto-binary-bytes]
      --selection-details           Show server selection details
      --ca-certificate=ARG          CA Certificate bundle path
  -v                                Logging verbosity. Specify multiple times for higher verbosity
      --output-header               Show output header for CSV and TSV formats

```

**Comment by obroomhall** [comment]
It seems I was using https://github.com/sivel/speedtest-cli which must have some issues resolving Ookla ids. Using Ookla's speedtest cli I was able to confirm the slow speeds are not related to docker networking. Though it does bring up the question of why I can get full speed results via the web interface and not by cli.
![Untitled](https://user-images.githubusercontent.com/4409652/203149622-3d78749e-5165-4b75-88b3-2081e77fa265.png)
I suspect it has something to do with the web interface using multiple servers to test on (but hiding that from the user `+3 more`)

**Comment by alexdelprete** [comment]
Did you select Multi or Single below the gauge?

![image](https://user-images.githubusercontent.com/7027842/203150620-dba27d53-6169-444b-bb26-0e541194b723.png)

**Comment by alexdelprete** [comment]
Single:

![image](https://user-images.githubusercontent.com/7027842/203151396-91f56963-0e15-4047-bfd7-4eaf35663a83.png)

Multi:

![image](https://user-images.githubusercontent.com/7027842/203151365-4338b007-eeee-443e-99c4-1f4aff16e6a3.png)

**Comment by obroomhall** [comment]
You're right, I was on multi, and that is a terrible server!
![image](https://user-images.githubusercontent.com/4409652/203151899-329cd2fc-b1b6-4817-9a9c-8e6224c5abd2.png)

**Comment by alexdelprete** [comment]
I told you so. :)

find a good server, and configure its ID in speedtest-tracker, so it will use only that one.
