### ISSUE TITLE
[Feature] Generate App Key with instructions on first load.

### ISSUE THREAD

**Issue by te5s3rakt** [alexjustesen/speedtest-tracker#1675]
**Is your feature request related to a problem? Please describe.**
With the introduction of an APP_KEY requirement in the configuration, users are now directed to generate a key when setting up.

This can be conveniently done at the address provided in the documentation. But this requires users to go to an external resource to set up the container.

**Describe the solution you'd like**
There exists the capability to generate a key from the containers console.

I suggest to check on load if the key is not provided, and if blank, generate a key for the user and print to screen with instructions to place it in the relevant ENV variable and reboot.

This way users can setup the container without having to go to an external resource.

**Comment by alexjustesen** [comment]
So this used to be the case where we'd generate a key on first boot but because people either store these keys as environment values in their `docker-compose.yml` files or physically in a `.env` it was more complex to cover the use cases.

I don't have any plans to revert back to that patten but I will keep it in mind going forward if an opportunity arises to improve the initial install. Thanks for the feedback!

**Comment by te5s3rakt** [comment]
So I’m not talking about changing that behaviour.

Just adding a print to the log that generates a key if null, with a note telling the user, “APP_KEY missing, one has been generated for you below, please place into docker ENV variable and reboot container”.

That way users that don’t populate a key will be provided instructions and a key to do so.
Users that do, well nothing will have changed.
