### ISSUE TITLE
TrueNAS Connection refused

### ISSUE THREAD

**Issue by matthewtrains** [alexjustesen/speedtest-tracker#616]
Dont need to say much more, i dont not know the propper PUID or anything related if thats the issue as in the log it hangs on "2023-05-26 00:05:04.189246+00:00🔒  Fixing app path file permissions..."

**Comment by matthewtrains** [comment]
2023-05-26 00:50:04.621796+00:00req: Can't open "/etc/ssl/web/ssl.key" for writing, Permission denied
2023-05-26 00:50:04.624737+00:00ln: failed to create symbolic link '/etc/nginx/sites-enabled/ssl-mixed': Permission denied
2023-05-26 00:50:04.625150+00:00s6-rc: warning: unable to start service configure-ssl: command exited 1
2023-05-26 00:50:04.627273+00:00/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
2023-05-26 00:50:04.627310+00:00prog: fatal: stopping the container.

**Comment by iambenmitchell** [comment]
same here

**Comment by alexjustesen** [comment]
@matthewtrains @iambenmitchell are y'all passing in custom certs?

**Comment by alfi0812** [comment]
Im having an similar issues in TrueNAS Scale. It stays in "🔒 Fixing app path file permissions..." for around 15mins and then proceeds to start normally (and then works like it should.) Seems to happen because of the permissions fixing. This happens each restart

when trying to run the commands manually you use in the docker the command:
"chown -R webuser:webgroup $WEBUSER_HOME" 
$WEBUSER_HOME = `/var/www/html`
seems to be causing the issue as even running it manually takes forever to run (Size of that folder is around 73M and 10642 files in it). 
Most of the size seems to be in a folder called "`vendor`" and 10468 files originate from that folder. 

TrueNas Scale seems to use Kubernets. (Im not to fimilar with those systems but i thought it would be helpful to mention)

Contents of vendor folder: 

```99K     akaunting
4.5K    autoload.php
119K    awcodes
48K     bin
2.2M    blade-ui-kit
136K    brick
63K     chrisullyott
596K    composer
129K    danharrin
63K     dflydev
3.2M    doctrine
94K     dragonmantank
471K    egulias
2.3M    ezyang
20M     filament
33K     fruitcake
24K     graham-campbell
855K    guzzlehttp
2.2M    influxdata
10M     laravel
156K    laravel-notification-channels
2.3M    league
1.6M    livewire
807K    maatwebsite
234K    maennchen
205K    markbaker
253K    masterminds
755K    monolog
42K     myclabs
4.4M    nesbot
377K    nette
1.5M    nikic
340K    nunomaduro
456K    phpdocumentor
4.4M    phpoffice
37K     phpoption
556K    phpstan
445K    psr
1.4M    psy
28K     ralouphie
853K    ramsey
61K     ryangjchandler
654K    spatie
268K    squirephp
6.6M    symfony
1.3M    tgalopin
87K     tijsverkoyen
247K    vlucas
958K    voku
61K     webmozart
```

Otherwise your system works great for me. Thanks for the amazing work

**Comment by alexjustesen** [comment]
@alfi0812 `vendor` is all the PHP dependencies currently loaded for the tool so it's going to be a bit on the bigger side. I don't have a way to test out TrueNAS at the moment in the home lab so unfortunately can't help with this issue much.
