### ISSUE TITLE
No server defined error

### ISSUE THREAD

**Issue by zackmuc** [alexjustesen/speedtest-tracker#618]
**Describe the bug**

I reduced the number of servers by removeing some server which always show slow results.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/4520343/f3819fa6-f272-4af8-9d88-3f01d5dbbd87)
this appears sincd about 1 week

No sometimes i get this error:

{"type":"log","timestamp":"2023-05-30T09:00:05Z","message":"Configuration - No servers defined (NoServersException)","level":"error"}

**To Reproduce**
1. Select Servers like me
2. let it run some time

**Expected behavior**
All speedtest should run
![image](https://github.com/alexjustesen/speedtest-tracker/assets/4520343/7e59029b-3c39-4a86-ab9f-cb88e8307bb7)

**Environment (please complete the following information):**
 - OS: Raspbianos docker
-  Architecture: [e.g. arm64, amd64]
 - Version [e.g. v1]

**Comment by zackmuc** [comment]
After i remove all servers everything works again, so must be a problem if there is only a reduced number of servers

**Comment by cford1080** [comment]
I ran into this error today and decided to check the database. Based on OP's comment about "removing some server," I would have expected that there would be a missing server ID in the settings (looking at it, an empty string in that array - please consider some database normalization), but there wasn't anything like that, despite the fact that I also had added, removed, and added more servers.

One of the gripes I had with the other speed test tracker image was the server ID not being logged to the results when the execution failed so that I could remove non-working servers. I think that would be a good addition to this project so that users can clean up non working server IDs when these failures occur. (assuming there was actually an ID to log)

**Comment by nicandris** [comment]
yeah same issue here. seems like removed servers stay in the seleccted servers config
![image](https://github.com/alexjustesen/speedtest-tracker/assets/284798/08af717a-b838-4ec6-b746-d0e0eafee4ff)

**Comment by alexjustesen** [comment]
When `Configuration - No servers defined (NoServersException)` is thrown this is from the Speedtest Tracker CLI, the server that was provided can't be reached to actually run the test against either due to maintenance or other reasons and not a result of the application missing a server.

These types of failure are planned for in a future release where I'll either "round robin" the tests or you can set a fallback server should the first not be accessable.
