### ISSUE TITLE
iPerf support 

### ISSUE THREAD

**Issue by alexjustesen** [alexjustesen/speedtest-tracker#64]
Relying on one service that isn't open source for tests isn't a great idea. This issue is to remind myself to explore adding support for iPerf.

https://iperf.fr/

**Comment by alexdelprete** [comment]
public iperf servers are rare, and when a user is doing a test, all other users receive a NACK, they have to wait for all other tests to complete.

open-source services for speedtests...would be great, but are there any reliable around?

**Comment by alexjustesen** [comment]
Initial thought behind this is hosting your own iPerf server so you don't have to worry about process locks on the public servers.

**Comment by alexdelprete** [comment]
how do I test my connectivity if I host an iperf server in the homelab? unless you mean hosting it on the cloud.

there's also this project: https://github.com/librespeed/speedtest

**Comment by alexjustesen** [comment]
Correct you'd host your own in the cloud, also good reminder on that project. I knew it was out there but had forgotten about it.

**Comment by alexdelprete** [comment]
you would need a cloud provider that has very good bandwidth, reliable service, with no limitations. it's not easy, that's why there are so few iperf3 servers to use.

**Comment by alexjustesen** [comment]
Correct and upload seems to the where a VPS might fall flat against testing (specially those of us with fiber having 1Gbps up and down).

Last year I did some research on VPS performance against some of the bigger providers out there. Results are getting aged so this is going to need an update. 
![image](https://user-images.githubusercontent.com/1144087/197548680-9ac6f2de-28a2-44fc-bc4c-2193afb118fe.png)

**Comment by alexdelprete** [comment]
Wow...4Gbit/s in DL? You have a 10Gb fiber? :)

Not many of us have a VPS I guess...what is the cost of a server like that?

**Comment by alexjustesen** [comment]
I've used [DigitalOcean](https://m.do.co/c/504aac1d3da2) (that is a referral link for $200 in credits should you want to play) for years and that's my preferred provider

**Comment by hansenc0705** [comment]
Wonder if fast.com is an option for another Speedtest service.

**Comment by alexjustesen** [comment]
> Wonder if fast.com is an option for another Speedtest service.

I know there is a hacky way to get an API token and use a npm library to test but it doesn't look like there is an "official" way

**Comment by bleomycin** [comment]
Just to leave another use case for this that I understand isn't popular but also doesn't seem to exist in any competing software either. When shopping for a VPS, or dedicated server, or even colocation provider it would be invaluable to be able to have detailed speed test logs to those services for say the first month to better understand if there is routing congestion at certain times of day between the client and the server that can or cannot be fixed.

I've gone through a ton of pain over the years literally having to ship/drive my selfhosted "homelab" server that I colocate because my home internet sucks between data centers hundreds of miles away because everything started off fine and then unfixable congestion, caused by my isp's route to the data center, cropped up and now my plex server is buffering endlessly. 

Pingplotter does an excellent job at identifying loss/jitter issues. Your software coupled with iperf support (or some other easily self-hosted speed test tool) would be invaluable for this admittedly niche use case.

**Comment by jwaugh** [comment]
> public iperf servers are rare, and when a user is doing a test, all other users receive a NACK, they have to wait for all other tests to complete.
> 
> open-source services for speedtests...would be great, but are there any reliable around?

I have absolutely NO issue ever running tests with the servers I use from here, and I've used at least a handful of them. 

https://github.com/R0GGER/public-iperf3-servers

**Comment by alexdelprete** [comment]
> https://github.com/R0GGER/public-iperf3-servers

wow...that is an amazing list, and it is maintained! :)

And he also provides a wonderful json of the maintained list: https://iperf3serverlist.net/serverlist.json

I tested a few servers and they're working, but I can't saturate my FTTH (a standard 1Gb/300Mb profile) in download (iperf3 option -R). I'll see if there's a way to open multiple connections for the test.

@alexjustesen that json is perfect to let users pick the iperf3 servers based on country, bandwidth of the server, etc.

**Comment by alexjustesen** [comment]
Now tracking in https://github.com/alexjustesen/speedtest-tracker/discussions/976.
