### ISSUE TITLE
Speedtest tracker caused my server useless

### ISSUE THREAD

**Issue by lucius100** [alexjustesen/speedtest-tracker#867]
**Describe the bug**
I just setup the speedtest tracker in my container, after queue speedtest , I can't ssh into my server, my portainer and all docker container goes offline, I still can access my nginx proxy manager at port 81, now I don't know how to revert this

**To Reproduce**
1. Setup speedtest tracker in docker
2. Click on  Queue speedtest
3. Voila, u just crashed the whole server.
4. Can't even ssh to the server, dead.

**Environment (please complete the following information):**
 - OS: Ubuntu 22 x86_64 Minimal
-  Architecture: Ubuntu 22 x86_64 Minimal
 - Browser : Brave
 - Version [e.g. v1]

**Logs**
Can't ssh to get the logs.

**Comment by alexdelprete** [comment]
> 3\. Voila, u just crashed the whole server.

You have no idea of what you're talking about, because you don't know how docker works. A container can't cause that kind of issue. You've done something else that broke your ENTIRE system. A container doesn't break the OpenSSH daemon.

Before setting up an app/service, you need to study a little bit, ignorance does not allow you to say things like that.

This is the problem with docker apps: kids or any ignorant thinks that they can edit a file and have an app up and running, without even knowing what docker is. A disgrace to the IT community.
