### ISSUE TITLE
Unsupported cipher error

### ISSUE THREAD

**Issue by bam7** [alexjustesen/speedtest-tracker#893]
Any thoughts on an unsupported cipher error?

Started with a fresh container, using MySQL and app key environment variable set.   Force HTTPS set to true but same error when set to false.   Data store permissions are good.   Im using the stock install parameters right off the documentation, but maybe i missed something.   Error below.

Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm.
[2023-11-09 22:13:20] production.ERROR: Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm. {"exception":"[object] (RuntimeException(code: 0): Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:55)

**Comment by alexjustesen** [comment]
This sounds like the format of the `APP_KEY` is incorrect. I'd recreate it and make sure your key is prefixed by `base64:`

**Comment by alexjustesen** [comment]
Closing, no updates from author

**Comment by molnarti** [comment]
I started to have the same problem since updating to 0.14.2.. I never had a cipher key set previously, after reading the logs I set the key generated by this site: https://generate-random.org/encryption-key-generator?count=1&bytes=32&cipher=aes-256-cbc&string=&password= 
but stil getting an error 
`production.ERROR: Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm. {"exception":"[object] (RuntimeException(code: 0): Unsupported cipher or incorrect key length. Supported ciphers are: aes-128-cbc, aes-256-cbc, aes-128-gcm, aes-256-gcm. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:55)`

i have also prefixed the generated key with `base64:`

The variable is set in a file at` /config/*.env`

Additionally I am using a global .env file containing UID, GID and other variables, which is placed next to the docker-compose.yaml

interestingly, when I open portainer, I can't see any variable called APP_KEY in the list, but I am not sure if this is supposed to be a docker type of variable or a variable just used internally but the app (not sure how that makes sense)
