### ISSUE TITLE
CORS issue on a reverse proxy

### ISSUE THREAD

**Issue by Deses** [alexjustesen/speedtest-tracker#914]
**Describe the bug**
I access the Speedtest tracker through `http:\\speedtest.unraid.nas`, and I'm having issues on Firefox (Librewolf actually) and Brave (Chrome too) because the charts.js library is trying to be retrieved from `http:\\unraid.nas:10030` thus, getting an error.

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource http://unraid.nas:10030/js/filament/widgets/components/chart.js?v=3.0.94.0 (Reason: CORS header 'Access-Control-Allow-Origin' missing).`

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

**ALSO**: The "Admin panel" button that takes you to the login screen also has the wrong URL, it's pointing to `http://unraid.nas:10030/admin` rather than `http://speedtest.unraid.nas/admin`.
Once in the admin panel, the left menu items correctly have the right URL

I suspect the cause for both issues is the same. 

**Environment:**
 - OS: Unraid
-  Architecture: amd64
 - Browser Brave, Librefox
 - Version 0.13.3

**Screenshots**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/1654959/f392152a-ddc4-4c8d-bfc3-60c43daa3d0a)

**Comment by Deses** [comment]
Setting the container variable `APP_URL` to `speedtest.unraid.nas` did not work.

**Comment by alexjustesen** [comment]
> Setting the container variable `APP_URL` to `speedtest.unraid.nas` did not work.

Did you set it to `https://speedtest.unraid.nas`?

**Comment by Deses** [comment]
No, i set it as `speedtest.unraid.nas`. Let me try that.

**Comment by alexjustesen** [comment]
After changing the variable did you restart the container?

**Comment by Deses** [comment]
Unraid stops and starts the container whenever you change something, but regardless of that, I manually restarted it and same deal.

**Comment by aedelbro** [comment]
@Deses I am also using Unraid, Chrome, and have the speedtest running behind a reverse proxy (Nginx Proxy Manager), and have no issues. CORS or the admin panel button described. 

My guess is it's how you're accessing the web service / have configured the reverse proxy.

In your screenshot in the first post, the current URL is missing. That would help rule out some issues.

**Comment by Deses** [comment]
Hm, interesting.

This is how I configured access to mine, pretty simple stuff:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/1654959/65de82f0-da58-4d5c-b52f-5e9494dbc876)

How does yours look?

**Comment by aedelbro** [comment]
@Deses This will be very dependent on your network configuration. How you have it configured in Unraid, and your DNS resolutions

Personally, I have all web traffic pointing to NPM, and all DNS records for my domain pointing to NPM. 

So `speedtest.internal.mydomain.com` -> `192.168.1.3` which is NPM. NPM forwards the speedtest domain to `192.168.1.10`, which is the IP of the speedtest docker container.

NPM config:
<img width="494" alt="Screenshot 2023-11-29 at 10 19 22 AM" src="https://github.com/alexjustesen/speedtest-tracker/assets/36162221/f8d67e41-6f85-4011-a9d2-652dd2bca2f5">

Unraid config:
<img width="1078" alt="Screenshot 2023-11-29 at 10 21 28 AM" src="https://github.com/alexjustesen/speedtest-tracker/assets/36162221/9e8755c9-44a0-46cb-aca8-ddacc5b65266">

Without anything else, make sure the NPM port (`10030` from your screenshot) is the `HTTP` port variable in the unraid config. 

It seems like you're viewing `unraid.nas:10030` in your browser instead of `speedtest.unraid.nas`, and are not hitting NPM. But again, can't be sure without more info.

**Comment by Deses** [comment]
The main difference I'm seeing between our configurations is that you are using a bridge network (br0) and I'm not.
Otherwise `speedtest.unraid.nas` is also pointing to `unraid.nas:80` which is the port my NPM docker is listening to, then NPM forwards to `speedtest.unraid.nas` maped to `unraid.nas:10030`.

I tried ro replicate your setup using the br0 network with no luck. :/ Are you accessing the webUI using a local-only hostname like my `unraid.nas` or are you using something else?

The thing is that I'm hosting lots of other things exactly using the same method and nothing else broke with a CORS problem after reverse-proxying them.

**Comment by alexjustesen** [comment]
https://github.com/alexjustesen/speedtest-tracker/issues/752#issuecomment-1865383915
