### ISSUE TITLE
Incorrect speeds (?)

### ISSUE THREAD

**Issue by danzkigg** [alexjustesen/speedtest-tracker#919]
**Describe the bug**
I've just installed speedtest running on docker (windows), and the speedtest results that I am getting are not what I expected.

I'm getting:
DL: 170 Mbps (avg)
UL: 100 Mbps (avg)

If I run the test on speedtest.net or fast.com I'm constantly getting:
DL: 950 Mbps (avg)
UL: 500 Mbps (avg)

**Screenshots**
*Speedtest-tracker results:*
<img src="https://i.imgur.com/PQbzt9k.png"></img>

*Speedtest.net results (using the same server)*
<img src="https://i.imgur.com/JxrO8P2.png"></img>

**Comment by Deses** [comment]
You are not using the same server. Try using the same server on both applications.

**Comment by danzkigg** [comment]
> You are not using the same server. Try using the same server on both applications.

Using the same server as speedtest-tracker (ORANGE Puteaux [id: 23884])
<img src="https://i.imgur.com/FMNMyq7.png"></img>
<img src="https://i.imgur.com/gRyCviE.png"></img>

Still the same results.

**Comment by alexjustesen** [comment]
Test results can vary pretty wildly by device, hell even browser. Docker networking on Windows doesn't have the same performance as if you were running it on a Linux based machine so I'm not surprised by these results and have seen them myself as well.

Since this is a known issue I'm going to close it and strongly recommend using the Docker instance on another machine.
